---
name: "Chapter Creator"
guid: "e22fb8f5-bc98-4f76-9be4-87de302a97ea"
version: "0.5.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Create chapters.xml from Media Segments"
description: >
  Create chapters.xml from Media Segments.
category: "General"
owner: "jellyfin"
artifacts:
  - "ChapterCreator.dll"
changelog: >
  changelog
