---
name: "Chapter Creator"
guid: "6B0E323A-4AEE-4B10-813F-1E060488AE90"
version: "0.4.0.0"
targetAbi: "10.10.3.0"
framework: "net8.0"
overview: "Create chapters.xml from Media Segments"
description: >
  Create chapters.xml from Media Segments.
category: "General"
owner: "jellyfin"
artifacts:
  - "ChapterCreator.dll"
changelog: >
  changelog
